apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ms31950bo-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ms31950bo-java-springboot-gitops